#!/bin/bash
cd  /efs/database-backups
declare -a LOOP=("fazebackend" "fazerecorder" "fazestats")
DATE=$(date +"%Y-%m-%d")

for i in "${LOOP[@]}"
do
    echo "Backing up mongodb databases $i to S3"

    FILENAME="$DATE-$i-production-mongodb.tar.gz"
    S3PATH="backup.fazeclan.com/databases/$1"
    TEMPPATH=`mktemp -d --tmpdir=/efs/database-backups`
    mongodump -d dev_$i -o "$TEMPPATH" && rm -rf "$FILENAME" && GZIP=-9 tar -zcf "$FILENAME" "$(basename $TEMPPATH)"
    rm -rf "$TEMPPATH"
    /home/ubuntu/scripts/s3cmd put --multipart-chunk-size-mb=5000 "$FILENAME" s3://$S3PATH/$FILENAME
    rm -rf "$FILENAME"

    echo "$FILENAME uploaded to $S3PATH/$FILENAME"
done

echo "DONE DONE DONE"